### PR TITLE
Tweaked formatting

### PR DESCRIPTION
**Pull request by rbenson**

### CODE REVIEW

**Comment by evilC** [comment]
The ** wrapping around the warning does not seem to render when I view.  
Any particular reason for this change? SEO?

**Comment by rbenson** [comment]
You used #'s (headings) to style the Readme.  Headings give structure to the doc, so a single # is a main heading/topic, ## is a sub heading/topic. You had ##### or something - which is a sub-sub-sub-sub-heading.

**Comment by evilC** [comment]
Yeah but when I preview the changed version, the warning at the top that I wanted bold and in-your-face is just normal text with ** around.

**Comment by evilC** [comment]
Ahh, I see, it's an accessibility thing.  
OK, will allow you to fiddle.  
Please make sure it get made apparent that UJR is discontinued and link to UCR.

**Pull request merged**
